/**
 * @file
 */
#ifndef __SYSLIMITS_H__
#define __SYSLIMITS_H__

#include "kconfig.h"

#define PIPE_BUF _PIPE_BUF
#define NAME_MAX _NAME_MAX
#define PATH_MAX _PATH_MAX
#define OPEN_MAX _OPEN_MAX
#define LINE_MAX _LINE_MAX
#define PTHREAD_KEYS_MAX _PTHREAD_KEYS_MAX
#define PTHREAD_DESTRUCTOR_ITERATIONS _PTHREAD_DESTRUCTOR_ITERATIONS

#endif
