#!/usr/bin/env python

import sys
import rtplot

if __name__ == '__main__':
    # check python version
    if sys.version_info[0] < 3:
        raise Exception("python 3 or a more recent version is required.")

    argc = len(sys.argv)
    if(argc != 2):
        print("rtplot [msg files directory]")
        exit(1)

    msg_dir_path = sys.argv[1]

    # load rtplot main program
    rtplot.main(msg_dir_path)
