#!/usr/bin/env bash
#
# What the system answers uname() with, which is what the build knows and the
# kernel does not. The file is only written when what it says has changed, so
# that building again does not rebuild what reads it.

set -e

out="$1"

revision=$(git describe --always --dirty --abbrev=10 2>/dev/null || echo unknown)

# The time the revision was made, not the time of this build: a build of the
# same revision says the same thing however many times it is run
date=$(git log -1 --format=%cd --date=format:'%a %b %e %H:%M:%S %Y' 2>/dev/null ||
       echo unknown)

new="/* Generated by scripts/gen-version.sh */
#ifndef __KERNEL_VERSION_H__
#define __KERNEL_VERSION_H__

#define __REVISION__ \"$revision\"
#define __BUILD_DATE__ \"$date\"
#define __USER_NAME__ \"$(whoami)\"

#endif"

if [ ! -f "$out" ] || [ "$(cat "$out")" != "$new" ]; then
    echo "$new" > "$out"
fi
